##服务端口
#server.port=8081
##数据库连接
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/exam_notice_fly?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
#spring.datasource.name=root
#spring.datasource.password=88888888
##mybatis配置
#mybatis.type-aliases-package=com.fly.fankun.model.entity
#mybatis.mapperLocations=classpath:mapper/*.xml
#
#spring.http.encoding.force=true
#spring.http.encoding.charset=UTF-8
#spring.http.encoding.enabled=true
server:
  port: 8088


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://106.15.249.213:5432/exam_tips?allowMultiQueries=true
    username: postgres
    password: 88888888
    # 以下为数据库连接池配置，比直接使用数据库的要好 https://blog.csdn.net/justlpf/article/details/80728529
#    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      maxWait: 60000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters:
        commons-log.connection-logger-name: stat,wall,log4j
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # 配置DruidStatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        reset-enable: false
        # 登录名、密码
        login-username: admin
        login-password: admin

swagger:
  enabled: true
  request:
    url:
    package: com.fly.fankun.controller
    ngnix:
  api:
    title: 服务API
mybatis:
  type-aliases-package: com.fly.fankun.model.entity
  mapper-locations: classpath:mapper/*.xml